### PR TITLE
Issue183- Refactor git operations and fix errors

### LINKED ISSUE #183: Refactor and better error handling in git operations
Trying to solve the "simple merge conflict" problem showed that the error handling in git operations is quite a mess.
Here's a few things I had in mind:

* Refactor all utility functions to a better place to make `services/git.ts` easier to read
* ~~Catch and throw proper errors in git actions~~
  * By examining the errors thrown it seems that simpleGit throws decent enough errors for normal operations. A bigger question is how we build our application to work with them...
* Test what is possible and/or makes sense to test

### PR DESCRIPTION
**Pull request by guotin**
closes #183 

Tried to make the git operations clearer but this was quite a difficult task. There were multiple error cases with our current implementation where commits are made with the local user details and I hope I fixed all of them for now. Also did some quite heavy refactoring because almost every function seemed to do different url string manipulations.

I tried to click through various merge conflict situations and didn't manage to break it but maybe you can.

#### Error cases fixed
* Application allowed doing local commits and this caused merge conflicts and errors if remote is updated and page refreshed. Current fix: removed the automatic pull operation from `cloneRepository` when the repo location already exists. Pulling newest changes to repo needs a lot of thinking, e.g. when to do it?
* Merge conflict didn't go back to the previous branch after conflict. Fixed by checking out the old branch when merge conflict occured.
* Made the repoStateQuery use a list of local branches instead of the mess that returns all the remotes as well. This was the original use case.

#### Refactoring
* All simpleGit operations moved to `utils/gitUtils.ts`. The simpleGit object is still passed around and don't know a better way to handle this.
* All string manipulations (like getting the repository folder from an url) collected under a couple of functions and they were moved to `utils/utils.ts`. Better filename needed?. Some test cases written for them.
* Separated some logic to functions, renamed things etc. Hope it's somehow better.

#### Future things to consider
I didn't change any of the current pushing logic. Currently the application allows to make local commits with the save button and only when the apollo context contains a `githubToken`, it tries to do the automatic merge and pushing to remote. We need to change at least the following things to somehow meet the intended use case:

* Get the user details for git operations from a `ServiceUser` that is inside the `context.currentUser` 
  * Somehow parsing which one to use is needed
  * Multiple github (or other) tokens need to be in the `context` as a some sort of a map or sent from frontend
  * This is a big tasks 
* User specific repos for allowing multiple users to use the application at the same time. I think this could now be done by changing the repoLocation string (the new function that returns it) to include the intended username.
* Set git config details when cloning the repo instead of doing it in commit operation.  
* When to pull newest changes (mentioned above in the error cases why this is a problem)

### CODE REVIEW

**Review by ilkkamaksy — APPROVED** [review]
A lot more clear now. The git related stuff in utils can be relocated when we have a more clear vision.

File: backend/src/utils/utils.ts [hunk 1]
```diff
@@ -16,3 +21,40 @@ const runShellCommand = async (command: string): Promise<string> => {
...
+  return rawCommitMessage
+    ? sanitizeCommitMessage(rawCommitMessage)
+    : `User ${username} modified file ${realFilename}`
+}
+
+export const getRepoLocationFromUrlString = (urlString: string): string => {
+  const url = new URL(urlString)
+  const repositoryName = url.pathname
+  const repoLocation = `./repositories${repositoryName}`
+  return repoLocation
```
Comment (tulma95) [inline backend/src/utils/utils.ts:54]: You can use getRepoLocationFromRepoName() function here to reduce repetitiveness

File: backend/src/utils/utils.ts [hunk 2]
```diff
@@ -16,3 +21,40 @@ const runShellCommand = async (command: string): Promise<string> => {
...
+export const getRepositoryFromFilePath = (file: File): string => {
+  return file.name.split('/').slice(0, 2).join('/')
+}
+
+export const getFileNameFromFilePath = (
+  file: File,
+  repositoryName: string
+): string => {
+  return file.name.replace(`${repositoryName}/`, '') || file.name
+}
```
Comment (tulma95) [inline backend/src/utils/utils.ts:34]: what is the purpose of `|| file.name` here?

File: backend/src/utils/utils.ts (hunk 1 above)
Comment (guotin) [reply backend/src/utils/utils.ts:54]: Not the same end result imo. One extra slash.

File: backend/src/utils/utils.ts (hunk 2 above)
Comment (guotin) [reply backend/src/utils/utils.ts:34]: Did not dare to change it because I thought it had some corner case and I haven't created the function. If it's pointless at all times then we can remove.

File: backend/src/utils/utils.ts [hunk 3]
```diff
@@ -16,3 +21,40 @@ const runShellCommand = async (command: string): Promise<string> => {
...
+
+export const writeToFile = (file: File): void => {
+  writeFileSync(`./repositories/${file.name}`, file.content)
+}
+
+export const makeCommitMessage = (
+  rawCommitMessage: string,
+  username: string,
+  realFilename: string
```
Comment (tulma95) [inline backend/src/utils/utils.ts:43]: Should `realFileName` be changed to `filePath`?

File: backend/src/utils/utils.ts (hunk 1 above)
Comment (tulma95) [reply backend/src/utils/utils.ts:54]: You are right. Didn't see the extra slash

File: backend/src/utils/utils.ts (hunk 2 above)
Comment (tulma95) [reply backend/src/utils/utils.ts:34]: I can't figure when we would return the `file.name` but lets keep it there so we don't break anything

**Review by tulma95 — APPROVED** [review]
